spring:
    profiles:
        active: dev

mybatis:
    mapperLocations: classpath:mapper/*.xml
    typeAliasesPackage: com.isoftstone.hrms.model

logging:
  level:
    org.springframework.web: ERROR
    com.isoftstone.hrms: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: /applog/hrms/application.log
